### PR TITLE
Room Vacancy And Lost & Found

### PR DESCRIPTION
**Pull request by Nailsonseat**
## Room Vacancy 

- Grid wise color coded tiles indicating vacancy.
- Display the name of occupant.*

## Lost and Found

- Custom image tile for displaying the listed item
- Item can be listed as Lost or Found
- Features image cropper and forces the selected image in 4:3 for consistent image size in the tiles
- Supports both camera and gallery for listing
- A button to launch dialer app, for a listing's phone number

<table>
  <tr>
    <td>Screenshot from 2024-02-06 14-26-20</td>
    <td>Screenshot from 2024-02-06 14-26-15</td>
  </tr>
  <tr>
    <td>Screenshot from 2024-02-06 14-50-57</td>
    <td>Screenshot from 2024-02-06 14-27-16</td>
  </tr>
  <tr>
    <td>Screenshot from 2024-02-06 14-26-49</td>
    <td></td>
  </tr>
  <tr>
    <td>Screenshot from 2024-02-06 14-51-10</td>
  </tr>
</table>

### CODE REVIEW

**Comment by Nailsonseat** [comment]
There are two things that are not in this PR:

- Remove a listing in lost and found
- Vaccate a room in room vacancy feature

Both of these need credentials of the logged in user to be stored locally on device but were not included in #14 but will be included in #19

**Comment by Nailsonseat** [comment]
Requesting review @henilp105

**Review by henilp105 — COMMENTED** [review]
Thanks @Nailsonseat, looks good to me, minor comments.

**Comment by Nailsonseat** [comment]
Thank you @henilp105 for the review

- The image is actually saved to a folder called uploads using the multer, i have moved the multer initilization to the middlewares folder for better readability [here](https://github.com/OpenLake/Smart-Insti-App/blob/10a038ec243b987ec0363015493843a2d28ffe46/backend/middlewares/multerConfig.js)
- The permissions you mentioned were added in the [commit](https://github.com/OpenLake/Smart-Insti-App/pull/9/commits/fa88b1b156aeec99c50724f027eac48df7b72fef#diff-01fcaf7b3602f25c001d9aa939e2a48d6c04a1dd4fd314c86fe5952d875859e4) for configuring the flutter awesome notifications package, you can expect notifications to be used in PR s for broadcast and chatrooms in the future
- I have made a .env to include the base url for the backend domain.

Also please ignore the failed workflow build, it is because the .env file is ignored by the gitignore but at the same time it is also mentioned in pubspec.yaml as an asset required by the dotenv package.

I will make a PR soon to edit the build workflow to make a empty .env by `touch .env` in the workflow to handle this error.

**Review by henilp105 — APPROVED** [review]

**Pull request merged**
