### PR TITLE
Admin Functions

### PR DESCRIPTION
**Pull request by Nailsonseat**
## Admin Functions (FOSS 2024)

- Layout based on latest android 14 
- Add Student, Faculty, Courses, Rooms and Mess Menus.
- Search among entries added entries.
- Features dummy entries for proper demonstration of features.
- Includes input field validators
- The admin home is set as default page as the auth flow has not been set up yet.
- Single entries edit on all the above resources will be added in future.

<table>
  <tr>
    <td>
      Screenshot 4
    </td>
    <td>
      Screenshot 2
    </td>
  </tr>
  <tr>
    <td>
      Screenshot 3
    </td>
    <td>
      Screenshot 1
    </td>
  </tr>
  <tr>
    <td>
      Screenshot 5
    </td>
    <td></td>
  </tr>
</table>

### CODE REVIEW

**Comment by Nailsonseat** [comment]
Requesting review @tusharbansal22 @henilp105

**Comment by henilp105** [comment]
Can you review this @Akshatji800 ?

**Comment by Akshatji800** [comment]
Hey @Nailsonseat any specific reason for going with provider ?

**Comment by Nailsonseat** [comment]
> Hey @Nailsonseat any specific reason for going with provider ?
> 

No, I went forward with what I have worked with mostly. But if you have any other state  manager in mind, I can migrate to it ASAP.

**Comment by Akshatji800** [comment]
> > Hey @Nailsonseat any specific reason for going with provider ?
> 
> No, I went forward with what I have worked with mostly. But if you have any other state manager in mind, I can migrate to it ASAP.

Yeah since we are not sure about provider state in future, we should avoid using that and can go with riverpod or bloc.

**Comment by Nailsonseat** [comment]
> > > Hey @Nailsonseat any specific reason for going with provider ?
> > 
> > No, I went forward with what I have worked with mostly. But if you have any other state manager in mind, I can migrate to it ASAP.
> 
> Yeah since we are not sure about provider state in future, we should avoid using that and can go with riverpod or bloc.

Sure, I can go forward with riverpod since it's a successor to provider, the migration should be faster with it.

**Comment by Akshatji800** [comment]
> > > > Hey @Nailsonseat any specific reason for going with provider ?
> > > 
> > > 
> > > No, I went forward with what I have worked with mostly. But if you have any other state manager in mind, I can migrate to it ASAP.
> > 
> > 
> > Yeah since we are not sure about provider state in future, we should avoid using that and can go with riverpod or bloc.
> 
> Sure, I can go forward with riverpod since it's a successor to provider, the migration should be faster with it.

Yeah sounds good. 👍 Make the changes to the same PR itself.

**Comment by Nailsonseat** [comment]
I have migrated app's state management to riverpod. Requesting review @Akshatji800 . All the above changes produce the same screenshots as above

**Comment by Akshatji800** [comment]
Is using seperate package for email validation necessary?

**Comment by Nailsonseat** [comment]
> Is using seperate package for email validation necessary?

Not really, i can replace the validation with regex

**Comment by Akshatji800** [comment]
> > Is using seperate package for email validation necessary?
> 
> Not really, i can replace the validation with regex

Exactly, avoid using external dependencies to the project for not required things as much as you can else maintaining the project in long run will be a challenge.

**Comment by Nailsonseat** [comment]
> > > Is using seperate package for email validation necessary?
> > 
> > 
> > Not really, i can replace the validation with regex
> 
> Exactly, avoid using external dependencies to the project for not required things as much as you can else maintaining the project in long run will be a challenge.

Good point, i have replaced email validator with a regex expression for validation

**Review by henilp105 — APPROVED** [review]
Thanks @Nailsonseat , Looks good to me.

**Pull request merged**
