### PR TITLE
Broadcasts screen frontend

### PR DESCRIPTION
**Pull request by SAISURYAtalla**
This PR introduces a new feature to the application, allowing administrators to broadcast announcements to users. The broadcast feature provides a way for administrators to disseminate important information or updates efficiently to all app users.

It consists of a Broadcasts screen where the users can view the broadcasts/announcements made . It has details such as 

1. title 
2. body 
3. date 

broadcast_1
broadcast_2

Requesting review @henilp105

### CODE REVIEW

**Comment by Aditya062003** [comment]
Kindly resolve the conflicts.

**Comment by SAISURYAtalla** [comment]
conflicts resolved and is ready for review @Aditya062003 @henilp105

**Review by henilp105 — CHANGES_REQUESTED** [review]
Thanks @SAISURYAtalla, Resolve conflicts and comments.

**Comment by SAISURYAtalla** [comment]
conflicts resolved and redundant code removed 
requesting re-review @henilp105 @Aditya062003

**Pull request merged**
